### ISSUE TITLE
Как запустить ваш пример на esp32?

### ISSUE THREAD

**Issue by Nakin72** [kharlashkin/MPU-9250DMP#2]
Если брать Пример i2cdevlib под MPU-6050, то после пары изменений его можно запустить на ESP32. С вашим пока что это сложно сделать. Сможете что нибудь подсказать или помочь?

**Comment by kharlashkin** [comment]
Честно не знаю. С esp32 никогда не доводилось сталкиваться. И даже не смогу подсказать в какую сторону двигаться.

**Comment by pgii** [comment]
В файле **MPU9250_9Axis_MotionApps41.h** :

Удалить строки:
```
typedef int8_t prog_int8_t;
typedef uint8_t prog_uint8_t;
typedef int16_t prog_int16_t;
typedef uint16_t prog_uint16_t;
typedef int32_t prog_int32_t;
typedef uint32_t prog_uint32_t;
```

Заменить все методы 
`min`
на 
`std::min<int>`
Должно выглядеть вот так
`getFIFOBytes(fifoBuffer, std::min<int>(fifoCount, 128))`

В файле **MPU9250.h**:

Строку

`#include <avr/pgmspace.h>`

заменить на

```
#ifdef __AVR__
#include <avr/pgmspace.h>
#else
//#define PROGMEM /* empty */
//#define pgm_read_byte(x) (*(x))
//#define pgm_read_word(x) (*(x))
//#define pgm_read_float(x) (*(x))
//#define PSTR(STR) STR
#endif
```

В файле **I2Cdev.cpp**:

Добавить
```
#ifndef BUFFER_LENGTH
#define BUFFER_LENGTH 32
#endif
```

Строки
`for (uint8_t k = 0; k < length; k += min(length, BUFFER_LENGTH))`
Заменить на
`for (uint8_t k = 0; k < length; k += min((int)length, BUFFER_LENGTH))`
